# Generated by Django 6.0.5, then hand-split.
#
# This migration contains ONLY the unmanaged (managed=False) mirrors of tables
# owned by wenda-quiz. It emits NO DDL — the tables already exist in the shared
# wenda_db. Its job is purely to (a) define wenda_live.User so the swappable
# AUTH_USER_MODEL dependency resolves, and (b) be recorded as applied so the
# already-applied contrib migrations (admin/auth) have a consistent history in
# the shared django_migrations table.
#
# Because it creates no tables, this migration is marked applied out-of-band
# (see the Phase 2 setup notes) rather than run. The real wenda_live-owned
# tables live in 0002_game_tables.

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('instructor', 'Instructor (Faculty)'), ('student', 'Student'), ('admin', 'Administrator')], default='student', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quiz_user',
                'ordering': ['-created_at'],
                'managed': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quiz_instructor',
                'ordering': ['department', 'subject'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionBankEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('topic', models.CharField(blank=True, default='', max_length=255)),
                ('blooms_taxonomy_level', models.CharField(choices=[('remembering', 'Remembering'), ('understanding', 'Understanding'), ('applying', 'Applying'), ('analyzing', 'Analyzing'), ('evaluating', 'Evaluating'), ('creating', 'Creating')], default='remembering', max_length=16)),
                ('options', models.JSONField()),
                ('correct_answer_text', models.CharField(max_length=255)),
                ('question_set_title', models.CharField(blank=True, max_length=255)),
                ('source_document', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'question_bank_questionbankentry',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subjects_subject',
                'ordering': ['name', 'code'],
                'managed': False,
            },
        ),
    ]
