# Generated by Django 6.0.5 on 2026-06-01 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenda_live', '0002_game_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=50, unique=True)),
                ('course', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=50)),
                ('year_level', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quiz_student',
                'ordering': ['year_level', 'section', 'student_number'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'subjects_subject_students',
                'ordering': ['subject', 'student'],
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='player',
            name='student_user',
            field=models.ForeignKey(blank=True, db_column='student_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='played_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('game', 'student_user'), name='uniq_player_student_per_game'),
        ),
    ]
