# Generated by Django 6.0.5 on 2026-06-02 04:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenda_live', '0003_student_subjectstudent_player_student_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveQuizGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('total_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Number of correct answers, as a decimal (mirrors QuizResult.total_score).', max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='correct_count / total_questions * 100.', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='wenda_live.gamesession')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='live_quiz_grades', to='wenda_live.student')),
            ],
            options={
                'db_table': 'kahoot_livequizgrade',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('game', 'student'), name='uniq_grade_per_student_per_game')],
            },
        ),
    ]
