# Generated by Django 6.0.5 on 2026-06-04 02:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenda_live', '0004_livequizgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livequizgrade',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='total_score / (POINTS_BASE * total_questions) * 100 — the gradeable %.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='livequizgrade',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Speed-weighted live score (sum of points_awarded / Player.score).', max_digits=9),
        ),
    ]
